name: Upload to PyPI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine bump2version

      - name: Increment package version
        run: |
          python3 -m bumpversion --current-version $(cat VERSION) patch VERSION

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Commit & Push changes
        run: |
          git config --global user.name 'axdjuraev'
          git config --global user.email 'axdjuraev@gmail.com'
          git commit -am 'bump-version'
          git push "${{ secrets.REPO_MAIN }}"

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --repository pypi dist/*
