name: Upload to PyPI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine bump2version

      - name: Increment package version
        run: |
          python3 -m bumpversion --current-version $(cat VERSION) patch VERSION

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Commit version change
        run: |
          git config user.name "axdjuraev"
          git config user.email "axdjuraev@gmail.com"
          git commit -a -m "Bump version"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_OF_GITHUB }}
          branch: main

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --repository pypi dist/*
